build:
  image: docker:19.03.1
  only:
    - tags
  stage: build
  services:
    - docker:19.03.1-dind
  script:
    - IFS="_" read CODE_VERSION DATA_VERSION <<<$CI_COMMIT_REF_NAME
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - ./build.sh $CODE_VERSION $DATA_VERSION
    - IMAGE_TAG=$CI_REGISTRY_IMAGE:$TAG
    - docker push $IMAGE_TAG
