build:
  image: docker:19.03.1
  only:
    - tags
  stage: build
  services:
    - docker:19.03.1-dind
  script:
    - CODE_VERSION=$(echo $CI_COMMIT_REF_NAME | cut -d'_' -f1)
    - DATA_VERSION=$(echo $CI_COMMIT_REF_NAME | cut -d'_' -f2,3)
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - |
      if [[ $CODE_VERSION == $DATA_VERSION ]] # single stage build
      then
        single_stage_build/build.sh $CI_COMMIT_REF_NAME
      else
        build.sh $CODE_VERSION $DATA_VERSION
      fi
    - IMAGE_TAG=$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_TAG
